version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/quickpoll
      - PORT=3000

  client:
    build: ./client
    container_name: client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mongodb_data: