services:
  - type: web
    name: quickpoll-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: quickpoll-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

databases:
  - name: quickpoll-mongodb
    databaseName: quickpoll
    user: quickpoll_user
    plan: free